### ISSUE TITLE
json unmarshal error when calling client.ListQueries

### ISSUE THREAD

**Issue by leighhopcroft** [VanceLongwill/ksql-go#6]
Calling `client.ListQueries(ctx)` (using ksqldb server v0.17.0) returns the following error:

```
unable to decode JSON response '<JSON_RESP>': json: cannot unmarshal array into Go value of type client.ExecResult
```

An example of a json response that causes this error is below:
```json
[
    {
        "@type": "queries",
        "statementText": "LIST QUERIES;",
        "queries": [
            {
                "queryString": "CREATE OR REPLACE TABLE SOME_TABLE WITH (KAFKA_TOPIC='SOME_TABLE', PARTITIONS=3, REPLICAS=1) AS SELECT * FROM SOME_OTHER_TABLE EMIT CHANGES;",
                "sinks": [
                    "SOME_TABLE"
                ],
                "sinkKafkaTopics": [
                    "SOME_TABLE"
                ],
                "id": "CTAS_SOME_TABLE_69",
                "statusCount": {
                    "RUNNING": 1
                },
                "queryType": "PERSISTENT",
                "state": "RUNNING"
            }
        ],
        "warnings": []
    }
]
```

Looking at the source code for `client.ListQueries` I've pinpointed the error to be in [exec.go#L92](https://github.com/VanceLongwill/ksql-go/blob/e6516f79a0091ef8e2c3741ccb7e6e2f6050a245/client/exec.go#L92). The json decode fails due to the following error:
```
json: cannot unmarshal array into Go struct field Query.queries.sinks of type string
```
This error is then ignored, and the code then proceeds to try to decode in to a single `ExecResult` instead, which also fails and returns the original error message above.

I believe that the problem is that although [descriptions.go#L23](https://github.com/VanceLongwill/ksql-go/blob/e6516f79a0091ef8e2c3741ccb7e6e2f6050a245/client/descriptions.go#L23) sets the type of `Query.Sinks` to be `string` (as per [ksqldb docs](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-rest-api/ksql-endpoint/#common-fields)), the actual response is returning an array of strings, so the `Query.Sinks` type should be `[]string` instead. Making this change resolves the error.

Interestingly, the above example respose also has some extra fields not included in the ksqldb docs which only mention `queryString`, `sinks` and `id`.

**Comment by VanceLongwill** [comment]
Thanks for reporting this. Would you be comfortable preparing a PR with the fix you mentioned? 

@swist maybe you could also look into fixing the ksqldb docs?

**Comment by VanceLongwill** [comment]
#9
